# Прод: снаружи :8080 → gunicorn внутри :8000

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python load_data.py &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      DB_ENGINE: postgres
      DB_HOST: db
      DB_PORT: "5432"
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      DB_CONN_MAX_AGE: "600"
      DJANGO_DEBUG: "0"
      ALLOWED_HOSTS: "72.56.36.164,127.0.0.1,localhost,[::1],*"
    ports:
      - "8080:8000"
    volumes:
      - /opt/shop/staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_prod_data:
